easyjob_api.settings:
  type: config_object
  label: 'Easyjob API settings'
  mapping:
    base_url:
      type: string
      label: 'Base url'
    user:
      type: string
      label: 'User'
    password:
      type: string
      label: 'Password'
    timestamp:
      type: string
      label: 'Last import timestamp'
